### PR TITLE
I06_translation_hu

### PR DESCRIPTION
**Pull request by jackosan**
Hungarian translation for the json file

### CODE REVIEW

**Comment by CrazyMarvin** [comment]
Thanks for your support and have a nice Hacktober, @jackosan! 🎃

**Comment by jackosan** [comment]
Thank you! Nice Hacktober to you too! :) 🦇 👻

**Comment by CrazyMarvin** [comment]
Are you available for translating the app store description too? It can be found in the `fastlane/metadata/android` folder.

**Comment by jackosan** [comment]
Sure, I'll translate the descriptions to Hungarian shortly! :) Sadly my japanese is not that good yet to take on that challenge

**Pull request merged**
